In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from statsmodels.formula.api import logit
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("C:/Users/atharv/OneDrive/Desktop/Year 2/SSDI/Invistico_Airline.csv", na_values ='?')

In [4]:
df.head(5)

satisfaction  Gender   Customer Type  Age   Type of Travel     Class  \
0    satisfied  Female  Loyal Customer   65  Personal Travel       Eco   
1    satisfied    Male  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Female  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Female  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Female  Loyal Customer   70  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   

   Food and drink  ...  Online support  Ease of Online booking  \
0               0  ...               2                       3   
1               0  ...               2                       3   
2               0  ...               2                       2   
3               0  ...               3                       1   
4               0  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 23 columns]

In [5]:
#DATA CLEANING
df.isna().sum()

satisfaction                           0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Seat comfort                           0
Departure/Arrival time convenient      0
Food and drink                         0
Gate location                          0
Inflight wifi service                  0
Inflight entertainment                 0
Online support                         0
Ease of Online booking                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Online boarding                        0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
dtype: int64

In [6]:
#REPLACING SPACES WITH _
df.columns = df.columns.str.replace(' ','_')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   satisfaction                       129880 non-null  object 
 1   Gender                             129880 non-null  object 
 2   Customer_Type                      129880 non-null  object 
 3   Age                                129880 non-null  int64  
 4   Type_of_Travel                     129880 non-null  object 
 5   Class                              129880 non-null  object 
 6   Flight_Distance                    129880 non-null  int64  
 7   Seat_comfort                       129880 non-null  int64  
 8   Departure/Arrival_time_convenient  129880 non-null  int64  
 9   Food_and_drink                     129880 non-null  int64  
 10  Gate_location                      129880 non-null  int64  
 11  Inflight_wifi_service              1298

In [8]:
#REPLACING NULL VALUES WITH MEDIAN
df['Arrival_Delay_in_Minutes'] = df['Arrival_Delay_in_Minutes'].fillna(df['Arrival_Delay_in_Minutes'].median())

In [9]:
df.isna().sum()

satisfaction                         0
Gender                               0
Customer_Type                        0
Age                                  0
Type_of_Travel                       0
Class                                0
Flight_Distance                      0
Seat_comfort                         0
Departure/Arrival_time_convenient    0
Food_and_drink                       0
Gate_location                        0
Inflight_wifi_service                0
Inflight_entertainment               0
Online_support                       0
Ease_of_Online_booking               0
On-board_service                     0
Leg_room_service                     0
Baggage_handling                     0
Checkin_service                      0
Cleanliness                          0
Online_boarding                      0
Departure_Delay_in_Minutes           0
Arrival_Delay_in_Minutes             0
dtype: int64

In [10]:
df.describe()

Age  Flight_Distance   Seat_comfort  \
count  129880.000000    129880.000000  129880.000000   
mean       39.427957      1981.409055       2.838597   
std        15.119360      1027.115606       1.392983   
min         7.000000        50.000000       0.000000   
25%        27.000000      1359.000000       2.000000   
50%        40.000000      1925.000000       3.000000   
75%        51.000000      2544.000000       4.000000   
max        85.000000      6951.000000       5.000000   

       Departure/Arrival_time_convenient  Food_and_drink  Gate_location  \
count                      129880.000000   129880.000000  129880.000000   
mean                            2.990645        2.851994       2.990422   
std                             1.527224        1.443729       1.305970   
min                             0.000000        0.000000       0.000000   
25%                             2.000000        2.000000       2.000000   
50%                             3.000000        3.000000       3.000000   
75%                             4.000000        4.000000       4.000000   
max                             5.000000        5.000000       5.000000   

       Inflight_wifi_service  Inflight_entertainment  Online_support  \
count          129880.000000           129880.000000   129880.000000   
mean                3.249130                3.383477        3.519703   
std                 1.318818                1.346059        1.306511   
min                 0.000000                0.000000        0.000000   
25%                 2.000000                2.000000        3.000000   
50%                 3.000000                4.000000        4.000000   
75%                 4.000000                4.000000        5.000000   
max                 5.000000                5.000000        5.000000   

       Ease_of_Online_booking  On-board_service  Leg_room_service  \
count           129880.000000     129880.000000     129880.000000   
mean                 3.472105          3.465075          3.485902   
std                  1.305560          1.270836          1.292226   
min                  0.000000          0.000000          0.000000   
25%                  2.000000          3.000000          2.000000   
50%                  4.000000          4.000000          4.000000   
75%                  5.000000          4.000000          5.000000   
max                  5.000000          5.000000          5.000000   

       Baggage_handling  Checkin_service    Cleanliness  Online_boarding  \
count     129880.000000    129880.000000  129880.000000    129880.000000   
mean           3.695673         3.340807       3.705759         3.352587   
std            1.156483         1.260582       1.151774         1.298715   
min            1.000000         0.000000       0.000000         0.000000   
25%            3.000000         3.000000       3.000000         2.000000   
50%            4.000000         3.000000       4.000000         4.000000   
75%            5.000000         4.000000       5.000000         4.000000   
max            5.000000         5.000000       5.000000         5.000000   

       Departure_Delay_in_Minutes  Arrival_Delay_in_Minutes  
count               129880.000000             129880.000000  
mean                    14.713713                 15.045465  
std                     38.071126                 38.416353  
min                      0.000000                  0.000000  
25%                      0.000000                  0.000000  
50%                      0.000000                  0.000000  
75%                     12.000000                 13.000000  
max                   1592.000000               1584.000000

In [11]:
#SCALING THE QUANTITATIVE DATA

In [12]:
df.head(100)

satisfaction  Gender   Customer_Type  Age   Type_of_Travel     Class  \
0     satisfied  Female  Loyal Customer   65  Personal Travel       Eco   
1     satisfied    Male  Loyal Customer   47  Personal Travel  Business   
2     satisfied  Female  Loyal Customer   15  Personal Travel       Eco   
3     satisfied  Female  Loyal Customer   60  Personal Travel       Eco   
4     satisfied  Female  Loyal Customer   70  Personal Travel       Eco   
..          ...     ...             ...  ...              ...       ...   
95    satisfied    Male  Loyal Customer   39  Personal Travel  Eco Plus   
96    satisfied    Male  Loyal Customer   37  Personal Travel       Eco   
97    satisfied  Female  Loyal Customer   12  Personal Travel       Eco   
98    satisfied    Male  Loyal Customer   64  Personal Travel       Eco   
99    satisfied    Male  Loyal Customer   46  Personal Travel  Eco Plus   

    Flight_Distance  Seat_comfort  Departure/Arrival_time_convenient  \
0               265             0                                  0   
1              2464             0                                  0   
2              2138             0                                  0   
3               623             0                                  0   
4               354             0                                  0   
..              ...           ...                                ...   
95             2554             0                                  2   
96             2387             0                                  2   
97             2152             0                                  2   
98             2141             0                                  2   
99             1068             0                                  2   

    Food_and_drink  ...  Online_support  Ease_of_Online_booking  \
0                0  ...               2                       3   
1                0  ...               2                       3   
2                0  ...               2                       2   
3                0  ...               3                       1   
4                0  ...               4                       2   
..             ...  ...             ...                     ...   
95               0  ...               5                       5   
96               0  ...               1                       1   
97               0  ...               2                       2   
98               0  ...               2                       4   
99               0  ...               4                       4   

    On-board_service  Leg_room_service  Baggage_handling  Checkin_service  \
0                  3                 0                 3                5   
1                  4                 4                 4                2   
2                  3                 3                 4                4   
3                  1                 0                 1                4   
4                  2                 0                 2                4   
..               ...               ...               ...              ...   
95                 1                 1                 3                3   
96                 3                 3                 2                3   
97                 2                 5                 1                4   
98                 2                 2                 3                2   
99                 2                 5                 3                2   

    Cleanliness  Online_boarding  Departure_Delay_in_Minutes  \
0             3                2                           0   
1             3                2                         310   
2             4                2                           0   
3             1                3                           0   
4             2                5                           0   
..          ...              ...                         ...   
95            2                5                           

In [13]:
df[['Flight_Distance','Departure_Delay_in_Minutes','Arrival_Delay_in_Minutes']] = scale(df[['Flight_Distance','Departure_Delay_in_Minutes','Arrival_Delay_in_Minutes']], with_mean = True, with_std = True)   

In [14]:
df.head(10)

satisfaction  Gender   Customer_Type  Age   Type_of_Travel     Class  \
0    satisfied  Female  Loyal Customer   65  Personal Travel       Eco   
1    satisfied    Male  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Female  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Female  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Female  Loyal Customer   70  Personal Travel       Eco   
5    satisfied    Male  Loyal Customer   30  Personal Travel       Eco   
6    satisfied  Female  Loyal Customer   66  Personal Travel       Eco   
7    satisfied    Male  Loyal Customer   10  Personal Travel       Eco   
8    satisfied  Female  Loyal Customer   56  Personal Travel  Business   
9    satisfied    Male  Loyal Customer   22  Personal Travel       Eco   

   Flight_Distance  Seat_comfort  Departure/Arrival_time_convenient  \
0        -1.671103             0                                  0   
1         0.469852             0                                  0   
2         0.152458             0                                  0   
3        -1.322552             0                                  0   
4        -1.584452             0                                  0   
5        -0.085102             0                                  0   
6        -1.708100             0                                  0   
7        -0.164937             0                                  0   
8        -1.858035             0                                  0   
9        -0.414180             0                                  0   

   Food_and_drink  ...  Online_support  Ease_of_Online_booking  \
0               0  ...               2                       3   
1               0  ...               2                       3   
2               0  ...               2                       2   
3               0  ...               3                       1   
4               0  ...               4                       2   
5               0  ...               2                       2   
6               0  ...               5                       5   
7               0  ...               2                       2   
8               0  ...               5                       4   
9               0  ...               2                       2   

   On-board_service  Leg_room_service  Baggage_handling  Checkin_service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   
5                 5                 4                 5                5   
6                 5                 0                 5                5   
7                 3                 3                 4                5   
8                 4                 0                 1                5   
9                 2                 4                 5                3   

   Cleanliness  Online_boarding  Departure_Delay_in_Minutes  \
0            3                2                   -0.386481   
1            3                2                    7.756204   
2            4                2                   -0.386481   
3            1                3                   -0.386481   
4            2                5                   -0.386481   
5            4                2                   -0.386481   
6            5                3                    0.060053   
7            4                2                   -0.386481   
8            4                4                   -0.386481   
9            4                2                    0.401521   

   Arrival_Delay_in_Minutes  
0                 -0.391644  
1                  7.547714  
2                 -0.391644  
3                 -0.391644

In [15]:
#CHECKING VIF

In [16]:
x = df.loc[:,['Flight_Distance','Departure_Delay_in_Minutes','Arrival_Delay_in_Minutes']] 

In [17]:
x

Flight_Distance  Departure_Delay_in_Minutes  Arrival_Delay_in_Minutes
0             -1.671103                   -0.386481                 -0.391644
1              0.469852                    7.756204                  7.547714
2              0.152458                   -0.386481                 -0.391644
3             -1.322552                   -0.386481                 -0.391644
4             -1.584452                   -0.386481                 -0.391644
...                 ...                         ...                       ...
129875        -0.243799                   -0.386481                 -0.391644
129876         0.102804                    4.183929                  4.085634
129877         0.329653                    3.684862                  3.851357
129878         0.456222                    4.682997                  4.944646
129879         2.264205                    4.472863                  4.450063

[129880 rows x 3 columns]

In [18]:
vif = pd.DataFrame()
vif['feature'] = x.columns

# calculate the VIF for each feature
vif['VIF'] = [variance_inflation_factor(x.values, i)
                          for i in range(len(x.columns))]

print(vif)                          

                      feature        VIF
0             Flight_Distance   1.012871
1  Departure_Delay_in_Minutes  12.573576
2    Arrival_Delay_in_Minutes  12.565593


In [19]:
x = x.drop(['Departure_Delay_in_Minutes'], axis= 1)

In [20]:
vif = pd.DataFrame()
vif['feature'] = x.columns

# calculate the VIF for each feature
vif['VIF'] = [variance_inflation_factor(x.values, i)
                          for i in range(len(x.columns))]

print(vif)   

                    feature       VIF
0           Flight_Distance  1.012188
1  Arrival_Delay_in_Minutes  1.012188


In [21]:
df = df.drop(['Departure_Delay_in_Minutes'], axis= 1)

In [22]:
#Mapping the categorical variables

In [23]:
df.columns

Index(['satisfaction', 'Gender', 'Customer_Type', 'Age', 'Type_of_Travel',
       'Class', 'Flight_Distance', 'Seat_comfort',
       'Departure/Arrival_time_convenient', 'Food_and_drink', 'Gate_location',
       'Inflight_wifi_service', 'Inflight_entertainment', 'Online_support',
       'Ease_of_Online_booking', 'On-board_service', 'Leg_room_service',
       'Baggage_handling', 'Checkin_service', 'Cleanliness', 'Online_boarding',
       'Arrival_Delay_in_Minutes'],
      dtype='object')

In [24]:
df['satisfaction'].unique()

array(['satisfied', 'dissatisfied'], dtype=object)

In [25]:
df['satisfaction'] = df['satisfaction'].map({'satisfied': 1, 'dissatisfied': 0})

In [26]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [27]:
df['Customer_Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [28]:
df['Type_of_Travel'].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [29]:
df['Class'].unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

In [30]:
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})
df['Customer_Type'] = df['Customer_Type'].map({'Loyal Customer': 1, 'disloyal Customer':0})
df['Type_of_Travel'] = df['Type_of_Travel'].map({'Personal Travel':1, 'Business travel':0})
df['Class'] = df['Class'].map({'Eco':0, 'Business': 2, 'Eco Plus': 1})

In [31]:
df.head()

satisfaction  Gender  Customer_Type  Age  Type_of_Travel  Class  \
0             1       0              1   65               1      0   
1             1       1              1   47               1      2   
2             1       0              1   15               1      0   
3             1       0              1   60               1      0   
4             1       0              1   70               1      0   

   Flight_Distance  Seat_comfort  Departure/Arrival_time_convenient  \
0        -1.671103             0                                  0   
1         0.469852             0                                  0   
2         0.152458             0                                  0   
3        -1.322552             0                                  0   
4        -1.584452             0                                  0   

   Food_and_drink  ...  Inflight_entertainment  Online_support  \
0               0  ...                       4               2   
1               0  ...                       2               2   
2               0  ...                       0               2   
3               0  ...                       4               3   
4               0  ...                       3               4   

   Ease_of_Online_booking  On-board_service  Leg_room_service  \
0                       3                 3                 0   
1                       3                 4                 4   
2                       2                 3                 3   
3                       1                 1                 0   
4                       2                 2                 0   

   Baggage_handling  Checkin_service  Cleanliness  Online_boarding  \
0                 3                5            3                2   
1                 4                2            3                2   
2                 4                4            4                2   
3                 1                4            1                3   
4                 2                4            2                5   

   Arrival_Delay_in_Minutes  
0                 -0.391644  
1                  7.547714  
2                 -0.391644  
3                 -0.391644  
4                 -0.391644  

[5 rows x 22 columns]

In [32]:
#SEPARATING INDEPENDENT AND DEPENDENT VARIABLES

In [33]:
y = df.loc[:,'satisfaction']

In [34]:
x = df.drop(['satisfaction'], axis = 1)

In [35]:
x.head()

Gender  Customer_Type  Age  Type_of_Travel  Class  Flight_Distance  \
0       0              1   65               1      0        -1.671103   
1       1              1   47               1      2         0.469852   
2       0              1   15               1      0         0.152458   
3       0              1   60               1      0        -1.322552   
4       0              1   70               1      0        -1.584452   

   Seat_comfort  Departure/Arrival_time_convenient  Food_and_drink  \
0             0                                  0               0   
1             0                                  0               0   
2             0                                  0               0   
3             0                                  0               0   
4             0                                  0               0   

   Gate_location  ...  Inflight_entertainment  Online_support  \
0              2  ...                       4               2   
1              3  ...                       2               2   
2              3  ...                       0               2   
3              3  ...                       4               3   
4              3  ...                       3               4   

   Ease_of_Online_booking  On-board_service  Leg_room_service  \
0                       3                 3                 0   
1                       3                 4                 4   
2                       2                 3                 3   
3                       1                 1                 0   
4                       2                 2                 0   

   Baggage_handling  Checkin_service  Cleanliness  Online_boarding  \
0                 3                5            3                2   
1                 4                2            3                2   
2                 4                4            4                2   
3                 1                4            1                3   
4                 2                4            2                5   

   Arrival_Delay_in_Minutes  
0                 -0.391644  
1                  7.547714  
2                 -0.391644  
3                 -0.391644  
4                 -0.391644  

[5 rows x 21 columns]

In [36]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: satisfaction, dtype: int64

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.3, random_state= 2,shuffle=True )

In [38]:
x_train.shape

(90916, 21)

In [39]:
#using logistic regression 

In [40]:
logr = LogisticRegression(max_iter=  800)
logr.fit(x_train,y_train)

LogisticRegression(max_iter=800)

In [48]:
y_predlg = logr.predict(x_test)

In [49]:
logr.score(x_test,y_test)

0.8324607329842932

In [50]:
print(y_predlg)

[0 0 1 ... 0 0 0]


In [51]:
from sklearn import metrics

In [53]:
metrics.confusion_matrix(y_test,y_predlg)

array([[14364,  3245],
       [ 3283, 18072]], dtype=int64)

In [54]:
#using K Nearest neighbours classifier

In [55]:
from sklearn.neighbors import KNeighborsClassifier

In [56]:
knnclf = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [57]:
knnclf.fit(x_train,y_train)

KNeighborsClassifier()

In [58]:
y_predknn = knnclf.predict(x_test)

In [59]:
knnclf.score(x_test,y_test)

0.9036803202956575

In [69]:
metrics.confusion_matrix(y_test,y_predknn)

array([[16173,  1436],
       [ 2317, 19038]], dtype=int64)

In [61]:
#Using Support Vector Machine classifier

In [62]:
from sklearn.svm import SVC

In [63]:
clfsvc = SVC(kernel= 'rbf', random_state= 42)

In [64]:
clfsvc.fit(x_train,y_train)

SVC(random_state=42)

In [65]:
y_predsvc = clfsvc.predict(x_test)

In [66]:
y_predsvc

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [67]:
clfsvc.score(x_test,y_test)

0.8662611641515244

In [68]:
metrics.confusion_matrix(y_test,y_predsvc)

array([[15234,  2375],
       [ 2836, 18519]], dtype=int64)

In [70]:
#Using Naive bayes classifier

In [71]:
from sklearn.naive_bayes import GaussianNB

In [72]:
clfnb = GaussianNB()

In [73]:
clfnb.fit(x_train,y_train)

GaussianNB()

In [74]:
ypred_nb = clfnb.predict(x_test)

In [76]:
metrics.accuracy_score(ypred_nb, y_test)

0.8186787804126886

In [78]:
metrics.confusion_matrix(y_test,ypred_nb)

array([[14081,  3528],
       [ 3537, 17818]], dtype=int64)

In [79]:
#Using Decision Tree Classifier

In [80]:
from sklearn.tree import DecisionTreeClassifier

In [81]:
clf_dt = DecisionTreeClassifier()

In [82]:
clf_dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [83]:
y_preddt = clf_dt.predict(x_test)

In [84]:
metrics.accuracy_score(y_preddt, y_test)

0.9367621394107382

In [85]:
metrics.confusion_matrix(y_test,y_preddt)

array([[16389,  1220],
       [ 1244, 20111]], dtype=int64)

In [86]:
#Using Random Forest Classifier

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
clf_rf = RandomForestClassifier(n_estimators= 10, criterion='entropy')

In [89]:
clf_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [90]:
ypred_rf = clf_rf.predict(x_test)

In [91]:
metrics.accuracy_score(ypred_rf, y_test)

0.9505954214146392

In [94]:
metrics.confusion_matrix(y_test,ypred_rf)

array([[17005,   604],
       [ 1321, 20034]], dtype=int64)

In [2]:
#accuracy = metrics.accuracy_score(y_test,y_predlg)